### ISSUE TITLE
Red Sandstone slab error setting block half

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryLib#102]
Getting this error when I try to set the StoneSlabProperties.Half.LOWER on a red sandstone slab:

    java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockState{block=minecraft:double_stone_slab2, properties=[seamless, variant]}

And this error when trying to set the seamless property on minecraft:double_stone_slab2:

    java.lang.IllegalArgumentException: Cannot set property PropertyBool{name=seamless, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockState{block=minecraft:stone_slab2, properties=[half, variant]}

Are the IDs of these two reversed?

**Comment by darkdiplomat** [comment]
yep they were reversed
