### ISSUE TITLE
Change position of time of /ban command

### ISSUE THREAD

**Issue by svdragster** [CanaryModTeam/CanaryLib#106]
The system right now makes it impossible to do a temporary ban with a reason.
I suggest moving the time infront of the reason -> /ban <player> [time] [reason]

**Comment by darkdiplomat** [comment]
There is nothing wrong with the temp ban with message system.
[08:04:10] [net.minecraft.server.network.NetHandlerLoginServer] [INFO]: com.mojang.authlib.GameProfile@5c0ed767[name=darkdiplomat] (/127.0.0.1:49869) lost connection: testing temp ban system, Your Ban will be lifted at2015.03.18, 09:04:02

**Comment by svdragster** [comment]
Can you show me the command you used?

**Comment by darkdiplomat** [comment]
/ban darkdiplomat testing temp ban system 5 m

Note: the temp ban system doesn't allow for complex times, you would have to use the lowest division, like for 2hours 30 minutes it would be "125 m"

**Comment by svdragster** [comment]
<entry>
    <banningPlayer>svdragster</banningPlayer>
    <id>33</id>
    <ip>xxx.xxx.xxx.xxx</ip>
    <issuedDate>1430164912</issuedDate>
    <player>ObviousHacker</player>
    <reason>test ban 10 m</reason>
    <unbanDate>-1</unbanDate>
    <uuid>e84223f7-f8dd-4ea4-8494-25ef9d27a1a9</uuid>
  </entry>
This doesn't seem to work using /ban ObviousHacker test ban 10 m
