### ISSUE TITLE
[API Request] PlayerRefrence.getEnderChestInventory()

### ISSUE THREAD

**Issue by clucky** [CanaryModTeam/CanaryLib#108]
From what I can see using NBTExplorer, regardless of whether a player is logged out or not, their EnderChest Inventory can still be accessed. Would it be possible to have .getEnderChestInventory() in the PlayerRefrence class instead of the Player class, that way I can view offline player's EnderChest inventories? I imagine there is a way to do this using MetaTags, however, I am unfamiliar with MetaTags, and from what I understand, they are discouraged.

**Comment by darkdiplomat** [comment]
There could be some unforeseen bugs with this, let me know if any issues arise.

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryMod/commit/1a5534bee24d3c3c30361997e8337d59ca2245b6

Viewing the inventory works now. Not sure if saving will function as intended yet though.
