### ISSUE TITLE
BlockType.toString() representing minecraft:log2 data values oddly

### ISSUE THREAD

**Issue by clucky** [CanaryModTeam/CanaryLib#118]
Messing around with some block data outputting, I realized that all of the minecraft:log2 directions and variants have a data value of 0, except for `variant: dark_oak` and `axis: y`, it has a data value of 1. This seems to be a bug to me, and is causing some minor inconveniences with my code. Is this a bug?

**Comment by clucky** [comment]
As well, I have a question. How can I represent all possible data values of a block within BlockType?

**Comment by clucky** [comment]
The same issue can be found with minecraft:log. The only logs which appear to have a different data value, are the `axis: y`. Is there a point in even having data values now that there are Block Properties?

**Comment by darkdiplomat** [comment]
Data values are used when blocks are stored to the region files (afaik), BlockType was never intended as a system to represent all block "states" just a way to difference the actual noticeable types (ie: oak logs vs birch logs)  BlockType should be used in conjunction with a (meta)data value for full precision.

**Comment by clucky** [comment]
There is the issue then with logs and their children and z counterparts not having the same data value as the y.

**Comment by clucky** [comment]
-children +x
