### ISSUE TITLE
Simulating right click on lever or button causes it to break.

### ISSUE THREAD

**Issue by Sasha91** [CanaryModTeam/CanaryLib#130]
I was playing around with some scriptcraft, when i found that simulating a right click on a lever or button, causes it to fall off and lay on the ground as an item.
I can only assume that this is a bug.

code piece:
var block;

function rightClick(event) {
block = event.getBlockClicked();
echo(event.player, "block registered");
}

exports.sim = function(player) {
echo(player, "now simulating right click");
if(block.rightClick(player)) {
echo(player, "success");
} else {
echo(player, "failure");
}
}

events.blockRightClick(rightClick);

**Comment by jamierocks** [comment]
This is not the correct place to get ScriptCraft help.

**Comment by Larry1123** [comment]
Yea this sounds to be something wrong in script craft and not canary. Confirm this to be a canary issue and reopen this with more info if it is.
