### ISSUE TITLE
Improve ServerListPingHook

### ISSUE THREAD

**Issue by jamierocks** [CanaryModTeam/CanaryLib#69]
# Required API for ServerListPlus
- [X] Client address
- [X] [Virtual Hosts](https://github.com/Minecrell/ServerListPlus/wiki/Virtual-Hosts) (get the address the client connected with)
- [X] Protocol version of client
- Response:
  - [X] Descriptions (MotD)
  - [ ] Version Name
  - [ ] Protocol version
  - [ ] Hide players (leave out player counts and sample completely, renders as `???` on the client)
  - [X] Online players
  - [X] Max players
  - [X] Player sample
  - [X] Favicon

They are already crossed off if Canary has that functionality.

**Comment by lexware** [comment]
Even if you do not want to allow modifying the version name and protocol version, would you allow plugins to hide the player count, you could do this fairly easy.
eg the plugin could setPlayer to null, you could check for that and remove the players field in the handshake packet (if it is null).
