### ISSUE TITLE
Rework world commands

### ISSUE THREAD

**Issue by tuxillator** [CanaryModTeam/CanaryLib#79]
Feature request for worlds:

1. add additional world commands
2. rework the world commands to leverage the subcommand feature, e.g.:
```
/world create
/world delete
/world load
/world list
/world info
```
list and info don't currently exist. List is obviously just a list of worlds, info would show detail about the world, like:
- state (loaded/unloaded)
- spawn coordinates
- memory consumed
- etc...

**Comment by darkdiplomat** [comment]
For /world info, probably won't be able to really tell you the memory usage a world has, but I can include details such as number of entities/players/load chunks, configuration details, etc...
