### ISSUE TITLE
BlockProperties Helper Errors

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryLib#98]
* Either RailProperties is missing applyPowered or there needs to be a property for powered, detector, and activator rails
* Need to be able to apply seamless property for double stone slabs
* RedstoneRepeaterProperties needs an applyFacing
* HugeMushroomProperties needs applyVariant
* CommandBlockProperties.apply should be renamed CommandBlockProperties.applyTriggered
* WeightedPressurePlateProperties.applyPowered should be renamed WeightedPressurePlateProperties.applyPower
* RedstoneComparatorProperties needs applyFacing
* Is hay axis applied by RotatedPillarProperties.applyAxis(block, BlockFace.Axis.Z);?

**Comment by darkdiplomat** [comment]
```Either RailProperties is missing applyPowered or there needs to be a property for powered, detector, and activator rails```
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/api/world/blocks/properties/helpers/RailPoweredProperties.html

```Need to be able to apply seamless property for double stone slabs```
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/api/world/blocks/properties/helpers/StoneSlabNewProperties.html
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/api/world/blocks/properties/helpers/StoneSlabProperties.html

```RedstoneRepeaterProperties needs an applyFacing\RedstoneComparatorProperties needs applyFacing```
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/api/world/blocks/properties/helpers/DirectionalBlockProperties.html   I'll make the classes extend the Directional as well

```HugeMushroomProperties needs applyVariant```
There is a method but the static keyword got missed

```WeightedPressurePlateProperties.applyPowered should be renamed WeightedPressurePlateProperties.applyPower```
WeightedPressurePlate property should be corrected to "power" as well

```Is hay axis applied by RotatedPillarProperties.applyAxis(block, BlockFace.Axis.Z);?```
yes

**Comment by toddharrison** [comment]
Cool. Everything looks good. I would add HopperProperties needs applyEnabled() and should there be a BlockFace.NONE for Pumpkins?

**Comment by darkdiplomat** [comment]
There is no BlockFace "NONE" internally

**Comment by 14mRh4X0r** [comment]
Also, I think it's pointless to add one, `null` would suffice.

**Comment by darkdiplomat** [comment]
null isnt allowed internally either, there is no longer a "No Face" as far as i can tell
